language: node_js
python: 
  - "3.6"
node_js: stable

notifications:
  email:
    recipients:
      - jeremy0523@126.com
    on_success: change # default: change
    on_failure: always # default: always

install:
  - npm install

script:
  - hexo generate

after_script:
  - cd ./public
  - git init
  - git config user.name "yangyuanming"
  - git config user.email "jeremy.zftt@gmail.com"
  - git add .
  - git commit -m "Update Blog By TravisCI With Build $TRAVIS_BUILD_NUMBER"
  # Github Pages
  - git push --force --quiet "https://${CI_TOKEN}@${GH_REF}" master:master 
  # Coding Pages
  - git push --force --quiet "https://yangyuanming:${CO_TOKEN}@${CO_REF}" master:master
  - git tag v0.0.$TRAVIS_BUILD_NUMBER -a -m "Auto Taged By TravisCI With Build $TRAVIS_BUILD_NUMBER"
  # Github Pages
  - git push --quiet "https://${CI_TOKEN}@${GH_REF}" master:master --tags


addons:
  apt:
    update: true

branches:
  only:
    - blog
